---
name: Exception-Lite
version: 0.999_001
author:
  - Elizabeth Grace Frank-Backman
abstract: ~
license: perl
requires:
  perl: '>= 5.8.8'
provides:
  DB:
    file: lib/Exception/Lite.pm
  Exception::Lite:
    file: lib/Exception/Lite.pm
generated_by: Module::Build version 0.26
